version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
     - .:/app
    command: python randocat2.py
    depends_on:
      - database

  database:
    image: postgres:10.3
    ports:
      - "5432:5432"
